language: java
sudo: false
install: true
jdk: oraclejdk8
 
script: mvn clean verify
script: mvn test
script: mvn test -f ./source/pom.xml
before_script: cd Evaluator/src/test/java/evaluator/controller
script:
- ./EvaluatorControllerTests.java test
before_script: cd Evaluator/src/test/java/evaluator/service
script:
- ./EvaluatorServiceTests.java test



