language: java
sudo: true
install: true
jdk: oraclejdk8
 
script: mvn clean verify
script: mvn test
before_script: cd Evaluator/src/test/java/evaluator/service
script: EvaluatorServiceTests.java test





